import type { ComputeFn } from "@/tools/types";
import { formatINR, formatPercent, toNonNegative, toPositive } from "../format";

export const computeRoas: ComputeFn = (values) => {
  const spend = toPositive(values.spend);
  const revenue = toNonNegative(values.revenue);
  if (spend === null) return { error: "Enter ad spend greater than zero." };
  if (revenue === null) return { error: "Enter the revenue generated by the ads (zero or more)." };

  const roas = revenue / spend;
  const profit = revenue - spend;

  let verdict: string;
  if (roas < 1) verdict = "Losing money — the ads return less than they cost, before any other expense.";
  else if (roas < 3) verdict = "Covers ad spend — whether it's profitable depends on your product margins.";
  else verdict = "Strong — well above the common 3x benchmark for healthy paid campaigns.";

  return {
    results: [
      { label: "ROAS", value: `${roas.toFixed(2)}x`, emphasis: true },
      { label: "ROAS percentage", value: formatPercent(roas * 100) },
      { label: "Net revenue after ad spend", value: formatINR(profit) },
      { label: "Verdict", value: verdict },
    ],
  };
};
