export const AUDIT_ACTIONS = {
  // AUTH
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  LOGOUT_ALL: "LOGOUT_ALL",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",
  TWO_FACTOR_ENABLED: "2FA_ENABLED",
  TWO_FACTOR_DISABLED: "2FA_DISABLED",
  UNAUTHORIZED_ADMIN_ACTION: "UNAUTHORIZED_ADMIN_ACTION",

  // TOOLS
  CREATE_TOOL: "CREATE_TOOL",
  UPDATE_TOOL: "UPDATE_TOOL",
  DELETE_TOOL: "DELETE_TOOL",
  PUBLISH_TOOL: "PUBLISH_TOOL",
  UNPUBLISH_TOOL: "UNPUBLISH_TOOL",
  ACTIVATE_TOOL: "ACTIVATE_TOOL",
  DEACTIVATE_TOOL: "DEACTIVATE_TOOL",
  DUPLICATE_TOOL: "DUPLICATE_TOOL",
  REORDER_TOOLS: "REORDER_TOOLS",
  BULK_UPDATE_TOOLS: "BULK_UPDATE_TOOLS",

  // CATEGORIES
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  MERGE_CATEGORY: "MERGE_CATEGORY",
  REORDER_CATEGORIES: "REORDER_CATEGORIES",
  ACTIVATE_CATEGORY: "ACTIVATE_CATEGORY",
  DEACTIVATE_CATEGORY: "DEACTIVATE_CATEGORY",

  // CONTENT
  CREATE_CONTENT: "CREATE_CONTENT",
  UPDATE_CONTENT: "UPDATE_CONTENT",
  DELETE_CONTENT: "DELETE_CONTENT",
  PUBLISH_CONTENT: "PUBLISH_CONTENT",
  UNPUBLISH_CONTENT: "UNPUBLISH_CONTENT",
  SCHEDULE_CONTENT: "SCHEDULE_CONTENT",

  // SEO
  UPDATE_SEO: "UPDATE_SEO",
  UPDATE_ROBOTS: "UPDATE_ROBOTS",
  UPDATE_SITEMAP: "UPDATE_SITEMAP",
  CREATE_REDIRECT: "CREATE_REDIRECT",
  UPDATE_REDIRECT: "UPDATE_REDIRECT",
  DELETE_REDIRECT: "DELETE_REDIRECT",

  // USERS
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  BLOCK_USER: "BLOCK_USER",
  UNBLOCK_USER: "UNBLOCK_USER",
  DELETE_USER: "DELETE_USER",
  CHANGE_USER_PLAN: "CHANGE_USER_PLAN",

  // ADMIN
  CREATE_ADMIN: "CREATE_ADMIN",
  UPDATE_ADMIN: "UPDATE_ADMIN",
  DISABLE_ADMIN: "DISABLE_ADMIN",
  ENABLE_ADMIN: "ENABLE_ADMIN",
  CHANGE_ROLE: "CHANGE_ROLE",
  REVOKE_SESSIONS: "REVOKE_SESSIONS",
  ADMIN_ROLE_ASSIGNED: "ADMIN_ROLE_ASSIGNED",
  ADMIN_STATUS_CHANGED: "ADMIN_STATUS_CHANGED",
  PRIVILEGE_ESCALATION_ATTEMPT: "PRIVILEGE_ESCALATION_ATTEMPT",

  // ROLES
  CREATE_ROLE: "CREATE_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  UPDATE_ROLE_PERMISSIONS: "UPDATE_ROLE_PERMISSIONS",

  // PAYMENTS
  PAYMENT_REFUND: "PAYMENT_REFUND",
  PAYMENT_PARTIAL_REFUND: "PAYMENT_PARTIAL_REFUND",

  // SUBSCRIPTIONS
  CREATE_SUBSCRIPTION: "CREATE_SUBSCRIPTION",
  UPDATE_SUBSCRIPTION: "UPDATE_SUBSCRIPTION",
  CANCEL_SUBSCRIPTION: "CANCEL_SUBSCRIPTION",

  // MEDIA
  UPLOAD_MEDIA: "UPLOAD_MEDIA",
  UPDATE_MEDIA: "UPDATE_MEDIA",
  DELETE_MEDIA: "DELETE_MEDIA",
  REPLACE_MEDIA: "REPLACE_MEDIA",

  // SETTINGS & ADS
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  CREATE_AD: "CREATE_AD",
  UPDATE_AD: "UPDATE_AD",
  DELETE_AD: "DELETE_AD",
  ACTIVATE_AD: "ACTIVATE_AD",
  DEACTIVATE_AD: "DEACTIVATE_AD",

  // AI & FEEDBACK & ERRORS
  CREATE_PROMPT_VERSION: "CREATE_PROMPT_VERSION",
  UPDATE_AI_CONFIGURATION: "UPDATE_AI_CONFIGURATION",
  ACTIVATE_AI_CONFIGURATION: "ACTIVATE_AI_CONFIGURATION",
  UPDATE_FEEDBACK: "UPDATE_FEEDBACK",
  ASSIGN_FEEDBACK: "ASSIGN_FEEDBACK",
  RESOLVE_FEEDBACK: "RESOLVE_FEEDBACK",
  UPDATE_ERROR_STATUS: "UPDATE_ERROR_STATUS",
  ASSIGN_ERROR: "ASSIGN_ERROR",
  RESOLVE_ERROR: "RESOLVE_ERROR",
  IGNORE_ERROR: "IGNORE_ERROR",

  // SYSTEM / COMPLIANCE / MAINTENANCE / SETTINGS
  EXPORT_AUDIT_LOGS: "EXPORT_AUDIT_LOGS",
  CLEANUP_AUDIT_LOGS: "CLEANUP_AUDIT_LOGS",
  CREATE_BACKUP: "CREATE_BACKUP",
  VERIFY_BACKUP: "VERIFY_BACKUP",
  DOWNLOAD_BACKUP: "DOWNLOAD_BACKUP",
  DELETE_BACKUP: "DELETE_BACKUP",
  START_RESTORE: "START_RESTORE",
  COMPLETE_RESTORE: "COMPLETE_RESTORE",
  FAILED_RESTORE: "FAILED_RESTORE",
  CLEAR_CACHE: "CLEAR_CACHE",
  REINDEX_DATA: "REINDEX_DATA",
  REBUILD_SITEMAP: "REBUILD_SITEMAP",
  ENABLE_MAINTENANCE_MODE: "ENABLE_MAINTENANCE_MODE",
  DISABLE_MAINTENANCE_MODE: "DISABLE_MAINTENANCE_MODE",
  SYSTEM_HEALTH_CHECK: "SYSTEM_HEALTH_CHECK",
  UPDATE_WEBSITE_SETTINGS: "UPDATE_WEBSITE_SETTINGS",
  UPDATE_GENERAL_SETTINGS: "UPDATE_GENERAL_SETTINGS",
  UPDATE_EMAIL_SETTINGS: "UPDATE_EMAIL_SETTINGS",
  UPDATE_SECURITY_SETTINGS: "UPDATE_SECURITY_SETTINGS",
  UPDATE_INTEGRATIONS_SETTINGS: "UPDATE_INTEGRATIONS_SETTINGS",
  SEND_TEST_EMAIL: "SEND_TEST_EMAIL",
  SEND_TEST_WEBHOOK: "SEND_TEST_WEBHOOK",
  UPDATE_EMAIL_TEMPLATE: "UPDATE_EMAIL_TEMPLATE",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS] | string;

export const TARGET_TYPES = [
  "Tool",
  "Category",
  "User",
  "Admin",
  "Role",
  "Content",
  "SEO",
  "Redirect",
  "Payment",
  "Subscription",
  "Media",
  "Ad",
  "AI",
  "Feedback",
  "Error",
  "Settings",
  "System",
  "Backup",
  "RestoreJob",
  "MaintenanceConfig",
  "GlobalSetting",
  "EmailTemplate",
] as const;

export type TargetType = (typeof TARGET_TYPES)[number] | string;

/**
 * Returns default severity for an action.
 */
export function getActionSeverity(action: string): "INFO" | "WARNING" | "CRITICAL" {
  if (
    action.includes("DELETE") ||
    action.includes("BLOCK") ||
    action.includes("REFUND") ||
    action === "PRIVILEGE_ESCALATION_ATTEMPT" ||
    action === "UNAUTHORIZED_ADMIN_ACTION" ||
    action === "LOGIN_FAILED" ||
    action === "CLEANUP_AUDIT_LOGS"
  ) {
    return "CRITICAL";
  }

  if (
    action.includes("UPDATE") ||
    action.includes("DISABLE") ||
    action.includes("CANCEL") ||
    action.includes("ROLE") ||
    action.includes("SETTINGS") ||
    action.includes("EXPIRED")
  ) {
    return "WARNING";
  }

  return "INFO";
}
